In [2]:
import pandas as pd
#import json
#import requests
#import pickle
df = pd.read_csv('dataReduced2.csv')
#df = df0.loc[df0['TARGET']!=2]
df.head(3)

SK_ID_CURR  TARGET  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  \
0      263934       1            1             0                0   
1      367366       0            1             0                1   
2      434796       0            1             0                0   

   CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
0             0          112500.0    270000.0      13500.0         270000.0   
1             0           45000.0    177903.0       8685.0         148500.0   
2             1          130500.0    153000.0       7812.0         153000.0   

   ...  CC_NAME_CONTRACT_STATUS_Signed_MAX  \
0  ...                               False   
1  ...                               False   
2  ...                               False   

   CC_NAME_CONTRACT_STATUS_Signed_MEAN  CC_NAME_CONTRACT_STATUS_Signed_SUM  \
0                                  0.0                                 0.0   
1                                  0.0                                 0.0   
2                                  0.0                                 0.0   

   CC_NAME_CONTRACT_STATUS_Signed_VAR  CC_NAME_CONTRACT_STATUS_nan_MIN  \
0                                 0.0                            False   
1                                 0.0                            False   
2                                 0.0                            False   

   CC_NAME_CONTRACT_STATUS_nan_MAX  CC_NAME_CONTRACT_STATUS_nan_MEAN  \
0                            False                               0.0   
1                            False                               0.0   
2                            False                               0.0   

   CC_NAME_CONTRACT_STATUS_nan_SUM  CC_NAME_CONTRACT_STATUS_nan_VAR  CC_COUNT  
0                              0.0                              0.0      12.0  
1                              0.0                              0.0      90.0  
2                              0.0                              0.0      12.0  

[3 rows x 805 columns]

In [17]:
df.index[df["SK_ID_CURR"] == 367366]

Int64Index([1], dtype='int64')

In [16]:
np.where(df["SK_ID_CURR"] == 367366)

(array([1]),)

In [9]:
dfclient = df.loc[df['SK_ID_CURR'] == 263934]
dfclient

SK_ID_CURR  TARGET  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  \
0      263934       1            1             0                0   

   CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
0             0          112500.0    270000.0      13500.0         270000.0   

   ...  CC_NAME_CONTRACT_STATUS_Signed_MAX  \
0  ...                               False   

   CC_NAME_CONTRACT_STATUS_Signed_MEAN  CC_NAME_CONTRACT_STATUS_Signed_SUM  \
0                                  0.0                                 0.0   

   CC_NAME_CONTRACT_STATUS_Signed_VAR  CC_NAME_CONTRACT_STATUS_nan_MIN  \
0                                 0.0                            False   

   CC_NAME_CONTRACT_STATUS_nan_MAX  CC_NAME_CONTRACT_STATUS_nan_MEAN  \
0                            False                               0.0   

   CC_NAME_CONTRACT_STATUS_nan_SUM  CC_NAME_CONTRACT_STATUS_nan_VAR  CC_COUNT  
0                              0.0                              0.0      12.0  

[1 rows x 805 columns]

In [11]:
X = pd.json_normalize(input.__dict__)
probability = float(model.predict_proba(X)[:, 1])
probability

ValueError: at least one array or dtype is required

In [10]:
dfclient = df.loc[df['SK_ID_CURR'] == 263934]
    
feats = [f for f in df.columns if f not in ['TARGET','SK_ID_CURR','SK_ID_BUREAU','SK_ID_PREV']]
X = dfclient[feats].values 
    
model = pickle.load(open('model.pkl', 'rb'))
result = model.predict_proba(X)
result

/Users/anne/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.2.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/anne/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 1.2.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(


array([[0.06929679, 0.93070321]])

In [12]:
result[0]

array([0.06929679, 0.93070321])

In [5]:
dfclient = df.loc[df['SK_ID_CURR'] == 100011]
data=json.dumps(dfclient.to_dict())
data

'{"index": {"0": 8}, "SK_ID_CURR": {"0": 100011}, "TARGET": {"0": 0.0}, "CODE_GENDER": {"0": 1}, "FLAG_OWN_CAR": {"0": 0}, "FLAG_OWN_REALTY": {"0": 0}, "CNT_CHILDREN": {"0": 0}, "AMT_INCOME_TOTAL": {"0": 112500.0}, "AMT_CREDIT": {"0": 1019610.0}, "AMT_ANNUITY": {"0": 33826.5}, "AMT_GOODS_PRICE": {"0": 913500.0}, "REGION_POPULATION_RELATIVE": {"0": 0.018634}, "DAYS_BIRTH": {"0": -20099}, "DAYS_EMPLOYED": {"0": 365}, "DAYS_REGISTRATION": {"0": -7427.0}, "DAYS_ID_PUBLISH": {"0": -3514}, "OWN_CAR_AGE": {"0": 1.0}, "FLAG_MOBIL": {"0": 1}, "FLAG_EMP_PHONE": {"0": 0}, "FLAG_WORK_PHONE": {"0": 0}, "FLAG_CONT_MOBILE": {"0": 1}, "FLAG_PHONE": {"0": 0}, "FLAG_EMAIL": {"0": 0}, "CNT_FAM_MEMBERS": {"0": 2.0}, "REGION_RATING_CLIENT": {"0": 2}, "REGION_RATING_CLIENT_W_CITY": {"0": 2}, "HOUR_APPR_PROCESS_START": {"0": 14}, "REG_REGION_NOT_LIVE_REGION": {"0": 0}, "REG_REGION_NOT_WORK_REGION": {"0": 0}, "LIVE_REGION_NOT_WORK_REGION": {"0": 0}, "REG_CITY_NOT_LIVE_CITY": {"0": 0}, "REG_CITY_NOT_WORK_CITY"

In [ ]:
#numpy_2d_arrays = np.array(dict["data"])
X = np.array(data)
X

In [ ]:
#data= json.loads(data)
#df2 = pd.DataFrame.from_dict(data)

from pandas import json_normalize
df2 = json_normalize(data)

In [12]:
request = requests.post(
    # url de FastAPI qui execute myapp.py
    url="http://127.0.0.1:8000/score_pret",
    #
    data=json.dumps(dfclient.iloc[0].to_dict()),
    headers={
        "Content-Type": "application/json",
    },
)

In [13]:
request.json()

{'detail': 'Not Found'}

In [ ]:
# Code de Tristan

In [10]:
# url de FastAPI qui execute myapp.py
request = requests.get(
    url="http://127.0.0.1:8000/exemple",
    headers={
        "Content-Type": "application/json",
    },
)

In [11]:
request.json()

{'resultat': 0.8}

In [8]:
df = pd.DataFrame([[3, 2]], columns=['var1', 'var2'])
df

var1  var2
0     3     2

In [9]:
request = requests.post(
    # url de FastAPI qui execute myapp.py
    url="http://127.0.0.1:8000/exemple_post",
    #
    data=json.dumps(clientID.iloc[0].to_dict()),
    headers={
        "Content-Type": "application/json",
    },
)

NameError: name 'clientID' is not defined

In [ ]:
request.json()

In [3]:
from lime import lime_tabular
dfclient = df.loc[df['SK_ID_CURR'] == 263934]
feats = [f for f in df.columns if f not in ['TARGET','SK_ID_CURR','SK_ID_BUREAU','SK_ID_PREV']]
dfclient = dfclient.drop(columns =['TARGET','SK_ID_CURR'])  

In [11]:
import pickle
model = pickle.load(open('model.pkl', 'rb'))

In [18]:
#X = dfclient[feats].values
X = df[feats].values
X

array([[1, 0, 0, ..., 0.0, 0.0, 12.0],
       [1, 0, 1, ..., 0.0, 0.0, 90.0],
       [1, 0, 0, ..., 0.0, 0.0, 12.0],
       ...,
       [0, 1, 1, ..., 0.0, 0.0, 10.0],
       [1, 1, 0, ..., 0.0, 0.0, 15.0],
       [1, 0, 1, ..., 0.0, 0.0, 14.0]], dtype=object)

In [22]:
X[idx].dtype

dtype('O')

In [19]:
# Définir l'explainer
explainer = lime_tabular.LimeTabularExplainer(X, mode="classification",
                                              feature_names=feats)

# L'appliquer à la ligne d'index 1
idx = df.index[df["SK_ID_CURR"] == 367366]
exp = explainer.explain_instance(X[idx], model.predict_proba)
# imprimer les 5 principaux features
for i in range(5):
    print(f"{exp.as_list()[i][0]}: {exp.as_list()[i][1]:.2f}")

ValueError: could not broadcast input array from shape (803,) into shape (1,)